# Generated by Django 3.1.4 on 2021-05-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.IntegerField(choices=[(0, 'Unkown'), (1, 'White'), (2, 'Black'), (3, 'Red'), (4, 'Yellow'), (5, 'Silver')], default=0)),
                ('gear', models.IntegerField(choices=[(0, 'Unknown'), (1, 'AT'), (2, 'MT')], default=0, verbose_name='TypeOfGear')),
                ('drive', models.IntegerField(choices=[(0, 'Unknown'), (1, 'FF'), (2, 'FR'), (3, '4WD'), (4, 'MIDSHIP')], default=0, verbose_name='TypeOfDrive')),
                ('body_type', models.IntegerField(choices=[(0, 'Unknown'), (1, 'FF'), (2, 'FR'), (3, '4WD'), (4, 'MIDSHIP')], default=0, verbose_name='BodyType')),
                ('model_year', models.PositiveIntegerField(null=True, verbose_name='model year')),
                ('plate_category', models.IntegerField(choices=[(1, 'compact car'), (2, '5 numbers'), (3, '3 numbers'), (4, '8 numbers')], default=0)),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='mileage')),
                ('latest_inspection_date', models.DateField(null=True, verbose_name='LastInspectionDate')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='shop name')),
                ('tel', models.CharField(max_length=15, verbose_name='telephon number')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='email')),
                ('pref', models.IntegerField(choices=[(1, '北海道'), (2, '青森'), (3, '岩手'), (4, '宮城'), (5, '秋田'), (6, '山形'), (7, '福島'), (8, '茨城'), (9, '栃木'), (10, '群馬'), (11, '埼玉'), (12, '千葉'), (13, '東京'), (14, '神奈川'), (15, '新潟'), (16, '富山'), (17, '石川'), (18, '福井'), (19, '山梨'), (20, '長野'), (21, '岐阜'), (22, '静岡'), (23, '愛知'), (24, '三重'), (25, '滋賀'), (26, '京都'), (27, '大阪'), (28, '兵庫'), (29, '奈良'), (30, '和歌山'), (31, '鳥取'), (32, '島根'), (33, '岡山'), (34, '広島'), (35, '山口'), (36, '徳島'), (37, '香川'), (38, '愛媛'), (39, '高知'), (40, '福岡'), (41, '佐賀'), (42, '長崎'), (43, '熊本'), (44, '大分'), (45, '宮崎'), (46, '鹿児島'), (47, '沖縄')])),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('area', models.CharField(max_length=20, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.URLField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='carmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
        migrations.AddField(
            model_name='car',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.shop'),
        ),
    ]
