# Generated by Django 3.1.4 on 2021-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.IntegerField(choices=[(0, 'Unkown'), (1, 'White'), (2, 'Black'), (3, 'Red'), (4, 'Yellow')], default=0),
        ),
    ]
