# Generated by Django 3.1.4 on 2021-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.IntegerField(choices=[(0, '未設定'), (1, 'SEDAN'), (2, 'COUPE'), (3, 'WAGON')], default=0, verbose_name='BodyType'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.IntegerField(choices=[(-1, '未設定'), (0, 'Unkown'), (1, 'White'), (2, 'Black'), (3, 'Red'), (4, 'Yellow'), (5, 'Silver')], default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.IntegerField(choices=[(-1, '未設定'), (0, 'Unknown'), (1, 'AT'), (2, 'MT')], default=0, verbose_name='TypeOfGear'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.PositiveIntegerField(default=0, verbose_name='model year'),
        ),
    ]
